import { Camera, LogOut, Trash2, UserRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useAuth } from "../context/AuthContext";
import http from "../api/http";
import toast from "react-hot-toast";

export default function Profile() {
  const { user, setUser, logout }=useAuth(); const [profile,setProfile]=useState(user); const [files,setFiles]=useState([]); const [saving,setSaving]=useState(false); const input=useRef();
  useEffect(()=>{http.get("/users/me").then(({data})=>{setProfile(data.user);setUser(data.user);})},[setUser]);

  const save=async e=>{e.preventDefault();setSaving(true);try{const {data}=await http.put("/users/me",profile);setProfile(data.user);setUser(data.user);toast.success("Profile updated.");}catch(err){toast.error(err.response?.data?.message||"Update failed.");}finally{setSaving(false)}};
  const upload=async()=>{if(!files.length)return;const fd=new FormData();files.forEach(f=>fd.append("profileImages",f));try{const {data}=await http.post("/users/me/images",fd);setProfile(data.user);setUser(data.user);setFiles([]);toast.success("Profile image uploaded.");}catch(err){toast.error(err.response?.data?.message||"Upload failed.");}};
  const delImage=async id=>{try{const {data}=await http.delete(`/users/me/images/${id}`);setProfile(data.user);setUser(data.user);toast.success("Image removed.");}catch(err){toast.error(err.response?.data?.message||"Could not remove image.");}};
  const primary=async id=>{const {data}=await http.put(`/users/me/images/${id}/primary`);setProfile(data.user);setUser(data.user);toast.success("Primary image updated.");};
  const deleteAccount=async()=>{if(!confirm("Delete your account and owned listings? This cannot be undone."))return;try{await http.delete("/users/me");await logout();location.href="/";}catch(err){toast.error(err.response?.data?.message||"Could not delete account.");}};

  return <div className="page profile-page"><div className="profile-hero"><div><p className="eyebrow">Your account</p><h1>Profile</h1><p className="muted">Manage your public profile and images.</p></div><button className="btn ghost" onClick={logout}><LogOut size={16}/> Log out</button></div>
    <div className="profile-grid">
      <div className="surface profile-card"><div className="profile-cover"><div className="profile-avatar-wrap">{profile?.primaryProfileImage?<img className="avatar avatar-xl" src={profile.primaryProfileImage} alt="Profile"/>:<div className="avatar avatar-xl avatar-fallback"><UserRound/></div>}<button className="camera-btn" onClick={()=>input.current?.click()}><Camera size={16}/></button></div></div><div className="profile-card-body"><h2>@{profile?.username}</h2><p className="muted">{profile?.email}</p><div className="progress-row"><span>Profile completeness</span><span>{Math.min(100,Math.round(([profile?.username,profile?.email,profile?.bio,profile?.location,profile?.primaryProfileImage].filter(Boolean).length/5)*100))}%</span></div><div className="progress"><span style={{width:`${Math.min(100,Math.round(([profile?.username,profile?.email,profile?.bio,profile?.location,profile?.primaryProfileImage].filter(Boolean).length/5)*100))}%`}}/></div></div></div>
      <form className="surface profile-form" onSubmit={save}><h2>Edit profile</h2><div className="form-grid"><label>Username<input value={profile?.username||""} onChange={e=>setProfile({...profile,username:e.target.value})}/></label><label>Email<input type="email" value={profile?.email||""} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label>Phone<input value={profile?.phone||""} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>Location<input value={profile?.location||""} onChange={e=>setProfile({...profile,location:e.target.value})}/></label></div><label>About<textarea value={profile?.bio||""} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><button className="btn primary" disabled={saving}>{saving?"Saving...":"Save profile"}</button></form>
    </div>
    <section className="surface"><div className="section-heading"><div><p className="eyebrow">Your gallery</p><h2>Profile images</h2></div><button className="btn secondary" onClick={()=>input.current?.click()}><Camera size={16}/> Add images</button></div><input ref={input} hidden type="file" accept="image/*" multiple onChange={e=>{setFiles([...e.target.files]);}}/><div className="preview-row profile-gallery">{(profile?.profileImages||[]).map(img=><div className="profile-image-item" key={img._id}><img src={img.url} alt="Profile gallery"/><div><button onClick={()=>primary(img._id)} className="btn tiny secondary">Set primary</button><button onClick={()=>delImage(img._id)} className="btn tiny danger"><Trash2 size={13}/></button></div></div>)}</div>{files.length>0&&<div className="form-actions"><span className="muted">{files.length} image{files.length>1?"s":""} selected</span><button className="btn primary" onClick={upload}>Upload selected</button></div>}</section>
    <section className="danger-zone"><div><h3>Delete account</h3><p className="muted">This also removes your owned listings and authored reviews.</p></div><button className="btn danger" onClick={deleteAccount}><Trash2 size={16}/> Delete account</button></section>
  </div>;
}
